vich_uploader:
    db_driver: orm

    mappings:
        profil_image:
            uri_prefix: /uploads/profil
            upload_destination: '%kernel.project_dir%/public/uploads/profil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        project_image:
            uri_prefix: /uploads/project
            upload_destination: '%kernel.project_dir%/public/uploads/project'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true